### ISSUE TITLE
Doesn't load initially in chrome without editing a file in ./src

### ISSUE THREAD

**Issue by rocifier** [devloco/react-scripts-wptheme#4]
Chrome shows a white page with `npm run start` until I make any change in a ./src/ files such as App.js, then react modifies the DOM. Haven't been able to determine why this is, as there are no console errors. `wptheme-scripts start` works immediately in Internet Explorer 11.

**Comment by devloco** [comment]
@rocifier wow... I missed this issue long ago. Anyway, this particular set of scripts isn't supported anymore. I came over here to archive it, when I noticed your issue.

If this is still an issue (I just made a new release a moment ago), would you mind re-posting this issue to the main `create-react-wptheme` repo?

Thanks!
